/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rockenbrew_JavaWMF_SJMI */

#ifndef _Included_com_rockenbrew_JavaWMF_SJMI
#define _Included_com_rockenbrew_JavaWMF_SJMI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rockenbrew_JavaWMF_SJMI
 * Method:    GetAvailDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_rockenbrew_JavaWMF_SJMI_GetAvailDevices
  (JNIEnv *, jobject);

/*
 * Class:     com_rockenbrew_JavaWMF_SJMI
 * Method:    Initialise
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rockenbrew_JavaWMF_SJMI_Initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_rockenbrew_JavaWMF_SJMI
 * Method:    Monitor
 * Signature: (Lcom/rockenbrew/JavaWMF/Receiver;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rockenbrew_JavaWMF_SJMI_Monitor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rockenbrew_JavaWMF_SJMI
 * Method:    Uninitialise
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_rockenbrew_JavaWMF_SJMI_Uninitialise
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
